name: Create tag on updated version
on:
  push:
    branches:
     - main

jobs:
  create-tag:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder:
          - azure
          - google
          - openid-connect
          - oauth2
          - keycloak
    outputs:
      version: ${{ steps.retrieve-version.outputs.version }}
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - id: retrieve-version
        run: |
          PACKAGE_VERSION=$(cat platforms/${{ matrix.folder }}/package.json \
          | grep unleash-server \
          | head -1 \
          | awk -F: '{ print $2 }' \
          | sed 's/[", ]//g')
          echo "::set-output name=version::${PACKAGE_VERSION}"
      - run: echo "Version = ${{ steps.retrieve-version.outputs.version }}"
      - uses: rickstaa/action-create-tag@v1
        continue-on-error: true
        with:
          tag: ${{ steps.retrieve-version.outputs.version }}
