name: Build and verify PR
on:
  pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - 20-alpine
        folder:
          - azure
          - google
          - openid-connect
          - oauth2
          - keycloak
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Setup QEmu so we can build multiplatform
        uses: docker/setup-qemu-action@v3
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker meta configuration
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: |
            renatomjr/unleash-community-${{ matrix.folder }}
          tags:
            type=edge,suffix=-${{ matrix.version }}
            type=semver,pattern={{ version }},event=tag,suffix=-${{ matrix.version }}
            type=semver,pattern={{ major.minor }},event=tag,suffix=-${{ matrix.version }}
      - name: Build tag and push image to Docker hub
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          push: false
          context: platforms/${{ matrix.folder }}
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            NODE_VERSION=${{ matrix.version }}
